

github: [KidiIT,KIDI-S-TECH]
patreon: KIDI'S TECH
open_collective: KIDI-S-TECH
ko_fi: KidiIT
tidelift:  npm/babel
community_bridge:  GitHub Developer Program
liberapay: KIDI-S-TECH
issuehunt: KidiIT
otechie: KIDI-S-TECH
lfx_crowdfunding: cloud-foundry
custom: [https://github.com/enterprises/httpsgithubcomkidiit, https://github.com/KidiIT]
