
github: [KidiIT,KIDI-S-TECH]
patreon: ifejikachichetam88@gmail.com
community_bridge:  GitHub Developer Program
custom: [https://github.com/enterprises/httpsgithubcomkidiit, https://github.com/KidiIT]
