

github: [KidiIT,KIDI-S-TECH]
patreon:  patreon.com/user?u=110509857
community_bridge:  GitHub Developer Program
custom: [https://github.com/enterprises/httpsgithubcomkidiit, https://github.com/KidiIT]
