
github: [KIDI’S TECH.com,kidiit]
patreon: KIDI'S-TECH@patreon.com
community_bridge: https://openprofile.dev/profile/kiditech
custom: [https://github.com/KIDI-S-TECH, https://github.com/KidiIT]
        

